version: '3.8'

services:
  mcp-service:
    build: .
    ports:
      - "8001:8001"
    environment:
      - ENVIRONMENT=development
      - MCP_HOST=0.0.0.0
      - MCP_PORT=8001
      - AWS_REGION=us-east-1
      - LOG_LEVEL=INFO
      - REDIS_URL=redis://redis:6379/0
    env_file:
      - .env
    depends_on:
      - redis
    networks:
      - mcp-network

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    networks:
      - mcp-network
    command: redis-server --appendonly yes
    volumes:
      - redis-data:/data

volumes:
  redis-data:

networks:
  mcp-network:
    driver: bridge